### ISSUE TITLE
Merge script improvement.

### ISSUE THREAD

**Issue by tanaka-takayoshi** [MicrosoftDocs/sql-docs.ja-jp#17]
I asked the script improvement to the original repository.
https://github.com/MicrosoftDocs/sql-docs/pull/264

Could you tell me how I should submit this PR to Japanese repository? Will it automatically be merged?

**Comment by CeciAc** [comment]
Thanks for your contribution, @tanaka-takayoshi 
After the source is fixed, it replicates in the localized versions
I'm closing this issue.
