### ISSUE TITLE
delete ”第一次世界大戦” ASAP

### ISSUE THREAD

**Issue by miyamam** [MicrosoftDocs/sql-docs.ja-jp#21]
"第一次世界大戦" means world war one. Wide World Importers is not mean "第一次世界大戦".
Could you delete these **negative stupid wrong** translation word **ASAP**?

**Comment by CeciAc** [comment]
Duplicated issue from the private repo
https://github.com/MicrosoftDocs/sql-docs-pr.ja-jp/issues/7
