### ISSUE TITLE
"ODBC 3。x" needs to be replaced with "ODBC 3.x"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/sql-docs.ja-jp#245]
https://docs.microsoft.com/ja-jp/sql/odbc/reference/syntax/sqlgetstmtoption-function?view=sql-server-2017

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
