### ISSUE TITLE
"以前のバージョン" three links are the same

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/sql-docs.ja-jp#262]
https://docs.microsoft.com/ja-jp/sql/database-engine/discontinued-database-engine-functionality-in-sql-server-2016?view=sql-server-2017

以前のバージョン
    ・SQL Server 2014 で廃止されたデータベース エンジンの機能)
    ・SQL Server 2012 で廃止されたデータベース エンジンの機能)
    ・SQL Server 2008 で廃止されたデータベース エンジンの機能)
 → three links are the same:
    "https://docs.microsoft.com/ja-jp/sql/database-engine/discontinued-database-engine-functionality-in-sql-server-2016"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 309582b2-c853-175c-7356-3dd0aa953312
* Version Independent ID: adedc202-6434-4482-0c61-0da816ffeef6
* Content: [SQL Server 2016 で廃止されたデータベース エンジンの機能 - SQL Server](https://docs.microsoft.com/ja-jp/sql/database-engine/discontinued-database-engine-functionality-in-sql-server-2016?view=sql-server-2017#previous-versions)
* Content Source: [docs/database-engine/discontinued-database-engine-functionality-in-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/database-engine/discontinued-database-engine-functionality-in-sql-server-2016.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #2172](https://github.com/MicrosoftDocs/sql-docs/issues/2172) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/2172

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
