### ISSUE TITLE
[ビュー] -> [表示]

### ISSUE THREAD

**Issue by tyochiai** [MicrosoftDocs/sql-docs.ja-jp#269]
「監査機能の使用状況および診断データ」のメニュー名が日本語版の SSMS と一致していません。

![SSMS_telemetry](https://user-images.githubusercontent.com/363199/59579458-e4be8300-9107-11e9-87f1-821ee9a54214.PNG)

SQL Server Management Studio						15.0.18131.0
Microsoft Analysis Services クライアント ツール						15.0.1347.0
Microsoft Data Access Components (MDAC)						10.0.17134.1
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.17134.0
Microsoft .NET Framework						4.0.30319.42000
オペレーティング システム						10.0.17134

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: da45fffc-0846-89fc-40b5-4e6d2390dd01
* Version Independent ID: 6b6a97f9-8527-131b-1580-566f54c3e7a2
* Content: [SQL Server Management Studio - 使用状況および診断データ (SSMS) - SQL Server](https://docs.microsoft.com/ja-jp/sql/ssms/sql-server-management-studio-telemetry-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/sql-server-management-studio-telemetry-ssms.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/ssms/sql-server-management-studio-telemetry-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by CeciAc** [comment]
こんにちは、@tyochiai

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@tyochiai

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/sql/ssms/sql-server-management-studio-telemetry-ssms?view=sql-server-2017

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
