### ISSUE TITLE
Is this command supported on SQLDW?

### ISSUE THREAD

**Issue by yuharucan** [MicrosoftDocs/sql-docs.ja-jp#278]
I run this command on SQLDW and it works well. Is this command supported on SQLDW?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1d00c860-cd18-c8b5-bea6-0c1017153ba3
* Version Independent ID: 30dd33e4-87e9-1560-0257-d297f620d737
* Content: [DBCC FLUSHAUTHCACHE (Transact-SQL) - SQL Server](https://docs.microsoft.com/ja-jp/sql/t-sql/database-console-commands/dbcc-flushauthcache-transact-sql?view=azuresqldb-current)
* Content Source: [docs/t-sql/database-console-commands/dbcc-flushauthcache-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/t-sql/database-console-commands/dbcc-flushauthcache-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by CeciAc** [comment]
Hello, @yuh

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
