### ISSUE TITLE
ドキュメント不整合（-gスタートアップオプション）

### ISSUE THREAD

**Issue by ry0uta** [MicrosoftDocs/sql-docs.ja-jp#435]
以下のページではSQL Server2016以降のバージョンで-gスタートアップオプションに関する記述が削除されていますが、

データベース エンジン サービスのスタートアップ オプション
https://docs.microsoft.com/ja-jp/sql/database-engine/configure-windows/database-engine-service-startup-options?view=sql-server-2017

以下のページではSQL Server 2017でもスタートアップオプション-gの記載が残っており、不整合が生じています。

sqlservr アプリケーション
https://docs.microsoft.com/ja-jp/sql/tools/sqlservr-application?view=sql-server-2017

また、-gの記述削除が意図的なものであるならば、以下のページにもSQL Server 2017に対する-gに関する言及が残っております。

https://docs.microsoft.com/ja-jp/sql/database-engine/configure-windows/server-memory-server-configuration-options?view=sql-server-2017#setting-the-memory-options-manually
--------------------
次に、max server memory で制御されない、潜在的 SQL Server メモリ割り当てに相当するメモリ量を差し引きます。この相当するメモリ量は、 スタック サイズ1* に計算した最大ワーカー スレッド2 を掛けたものにスタートアップ パラメーター3 の -g を足して 求められます ( -g が設定されていない場合、既定で 256MB を足します)。 残ったものが単一インスタンス セットアップの max_server_memory 設定になります。
--------------------

SQL Server 2016以降について-gパラメータがサポートされるかが判断できない為、明確化をお願いします。
余談となりますが非サポートとなる場合は過去バージョンで-g で管理されたmemory_to_reserveのメモリ設定の扱いはどのようになるのでしょうか。（2016以降では設定を変更すること自体が非推奨？）

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 49ff7ba8-ef34-2020-0a3b-ee8e529d528e
* Version Independent ID: 8d086f94-2f89-db73-3ac9-60c1086e3262
* Content: [sqlservr.exe アプリケーション - SQL Server](https://docs.microsoft.com/ja-jp/sql/tools/sqlservr-application?view=sql-server-2017)
* Content Source: [docs/tools/sqlservr-application.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/tools/sqlservr-application.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by srvbpigh** [comment]
Hello, @ry0uta
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #2601](https://github.com/MicrosoftDocs/sql-docs/issues/2601) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@ry0uta
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/sql-docs/issues/2601) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
