### ISSUE TITLE
Can't download SSMS 18.3

### ISSUE THREAD

**Issue by nuitsjp** [MicrosoftDocs/sql-docs.ja-jp#781]
[フィードバックをこちらに入力してください]

SSMS 18.3 link is incorrect.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [SQL Server Management Studio (SSMS) のダウンロード - SQL Server](https://docs.microsoft.com/ja-jp/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @nuitsjp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
こんにちは、@nuitsjp

リンクは、次のローカライズラウンドで自動的に更新されます。 英語ファイルのリンクは正しいです。

ご協力ありがとうございます。
