### ISSUE TITLE
Replacees

### ISSUE THREAD

**Issue by yoichinak** [MicrosoftDocs/sql-docs.ja-jp#789]
In the commit https://github.com/MicrosoftDocs/sql-docs.ja-jp/commit/140aea627dda9dbe35a71e1a88599d3a78730f46 and https://github.com/MicrosoftDocs/sql-docs.ja-jp/commit/f6328e0ee98c0fa85b5e013b6ec66329001dd46f , troubles of replacees like #773 are occuring again.

**Comment by srvbpigh** [comment]
Hello, @yoichinak
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @yoichinak 
Thank you for your feedback.
This is a know global issue, we expect it to be fixed within the next week

Kind regards,
Microsoft DOCS International Team
