### ISSUE TITLE
Download link is wrong.

### ISSUE THREAD

**Issue by K-Ubu** [MicrosoftDocs/sql-docs.ja-jp#790]
About "https://docs.microsoft.com/ja-jp/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017"

When I click the link of "Download SQL Server Management Studio 18.3" , I navigated to the site "https://www.microsoft.com/ja-jp/?ref=go".
Please confirm the right link.
I could download "SQL Server Management Studio 18.2" from "https://docs.microsoft.com/ja-jp/sql/ssms/release-notes-ssms?view=sql-server-2017#previous-ssms-releases".
But I cannot use the latest version!

**Comment by srvbpigh** [comment]
Hello, @K-Ubu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @K-Ubu 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
