### ISSUE TITLE
テーブルレイアウトが崩れている

### ISSUE THREAD

**Issue by urimaro** [MicrosoftDocs/sql-docs.ja-jp#943]
テーブルのレイアウトが崩れています。
適切に改行されていないことが原因のように思われます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 441d7622-3d30-34cd-6cb1-b33882197be5
* Version Independent ID: 6ad33da3-3a42-ca4b-542c-df2c695a24c5
* Content: [sys.syslanguages (Transact-sql) - SQL Server](https://docs.microsoft.com/ja-jp/sql/relational-databases/system-compatibility-views/sys-syslanguages-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-compatibility-views/sys-syslanguages-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/relational-databases/system-compatibility-views/sys-syslanguages-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by srvbpigh** [comment]
Hello, @urimaro
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@urimaro  様:

投稿いただき、ありがとうございます。

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。

サポートいただきありがとうございます。

Microsoft DOCS グローバル エクスペリエンス チーム
