### ISSUE TITLE
レイアウト崩れ

### ISSUE THREAD

**Issue by eltociear** [MicrosoftDocs/sql-docs.ja-jp#944]
こちらのコンテンツ内容のレイアウトが崩れており見にくい内容となってしまっております。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1398236a-f5b5-df3f-424b-3b7cb8d441a2
* Version Independent ID: fd6bb4ee-ce44-878a-fc7f-6fa92406aed9
* Content: [sp_helpsort (Transact-sql) - SQL Server](https://docs.microsoft.com/ja-jp/sql/relational-databases/system-stored-procedures/sp-helpsort-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-helpsort-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/relational-databases/system-stored-procedures/sp-helpsort-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srvbpigh** [comment]
Hello, @eltociear
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@eltociear  様:

投稿いただき、ありがとうございます。

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。

サポートいただきありがとうございます。

Microsoft DOCS グローバル エクスペリエンス チーム

**Comment by eltociear** [comment]
@CeciAc 
了解です、ご確認頂きありがとうございした
