### ISSUE TITLE
ページレイアウト崩れ

### ISSUE THREAD

**Issue by eltociear** [MicrosoftDocs/sql-docs.ja-jp#947]
こちらのページ前半部分にてレイアウト崩れが発生しております
ご確認お願いいたします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2d95ec6f-3b85-8d5b-2111-8c10f11dcc1a
* Version Independent ID: 15bd8fa1-dd1b-80ff-c244-4b3dfa3b7049
* Content: [sys. databases (Transact-sql) - SQL Server](https://docs.microsoft.com/ja-jp/sql/relational-databases/system-catalog-views/sys-databases-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-databases-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/relational-databases/system-catalog-views/sys-databases-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srvbpigh** [comment]
Hello, @eltociear
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
こんにちは、@eltociear  

 フィードバックをお送りいただきありがとうございました。問題のページは機械翻訳されており、常に完全に理解可能であるとは限りません。最近、右側に "英語で読む" オプションが追加されました。このオプションを使用すると、言語設定を変更しなくても英語バージョンに切り替えることができます。  

 敬具  

Microsoft DOCS International Team

**Comment by eltociear** [comment]
@V-vafune 了解いたしました、ご確認頂きありがとうございます！
