### ISSUE TITLE
It is better to declare `SQLUSMALLINT iCol;`, isnt it ?

### ISSUE THREAD

**Issue by soumunote** [MicrosoftDocs/sql-docs.ja-jp#974]
[odbcsql.cpp]

Variable `iCol` is declared as SQLSMALLINT.
But, SQLColAttribute() s 2nd argument is declared as SQLUSMALLINT.

It is better to declare `SQLUSMALLINT iCol;`, isnt it ?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ac828919-7780-c626-d071-724e0cbc5d56
* Version Independent ID: 47d85824-56f3-9fa1-4348-30c864bc756b
* Content: [SQL データベースにアクセスする C++ ODBC アプリ - SQL Server](https://docs.microsoft.com/ja-jp/sql/connect/odbc/cpp-code-example-app-connect-access-sql-db?view=sql-server-ver15#feedback)
* Content Source: [docs/connect/odbc/cpp-code-example-app-connect-access-sql-db.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/connect/odbc/cpp-code-example-app-connect-access-sql-db.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by srvbpigh** [comment]
Hello, @soumunote
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by David-Engel** [comment]
@soumunote If you want to match the parameter types, yes, you would be correct. But there is no practical difference in memory usage or functionality by using SQLSMALLINT since there can't be more than 4.096 columns in a result. The conversion between SQLSMALLINT and SQLUSMALLINT will happen implicitly since the value of iCol will always be with the range of SQLUSMALLINT.

**Comment by CeciAc** [comment]
Hello, @soumunote 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
